language: cpp
compiler: clang
dist: bionic
before_install:
    - sudo apt-get install -y liblua5.2 liblua5.2-dev lua5.2
script: make GENERIC && make && make unittest && bin/unittest
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: bin
    on:
        branch: master
